### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 개좌 개설
POST http://localhost:8080/api/v1/account
Content-Type: application/json
Authorization: Bearer eyJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiZGlyIn0..C271uRTMLp30kPzr.eQ4bHnPaoiQWhl2Bh0DCIoMo4WG0TAsxdRdud2h9Dy6Tz9wfbtBZaTNyN67s3IwKtSCWMDMh6bG1IjBQm2d_ixPFQlwk3H2IjNKK0in7Ghrrzv7iz7TPpQbkwA.FC8EiPWe5l_Wlj0BNaB2wg