apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk
  name: filebeat-config
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: container
        paths:
          - "/var/lib/docker/containers/*/*.log"
          
    output.logstash:
      hosts: ["logstash-svc:5044"]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: elk
  name: filebeat
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat-oss:7.10.2
          args: ["-e"]
          securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 300Mi
          volumeMounts:
            - mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
              readOnly: true
              name: filebeat-config
            - mountPath: /var/lib/docker/containers
              readOnly: true
              name: container-log
      volumes:
        - name: filebeat-config
          configMap:
            name: filebeat-config
            items:
              - key: filebeat.yml
                path: filebeat.yml
        - name: container-log
          hostPath:
            path: /var/lib/docker/containers