# Config Map
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk
  name: kibana-config
data:
  kibana.yml: |-
    server.host: 0.0.0.0
    elasticsearch.hosts: http://elasticsearch-0.elasticsearch-svc:9200
---
# 서비스
apiVersion: v1
kind: Service
metadata:
  namespace: elk
  name: kibana-svc
  labels:
    app: kibana
spec:
  type: NodePort
  # 통신을 받을 파드를 찾기 위한 설정
  selector:
    app: kibana
  ports:
    - nodePort: 30601
      port: 5601
      targetPort: kibana-port
---
# 디플로이먼트 리소스
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: elk
  name: kibana
  labels:
    app: kibana
# deployment 사양
spec:
  # 파드 수
  replicas: 1
  # deployment 의 대상이 되는 파드 수를 찾기 위한 설정
  selector:
    matchLabels:
      app: kibana
  # Deployment 리소스가 생성할 파드의 메타 데이터
  # 하드 템플릿
  template:
    metadata:
      labels:
        app: kibana
    spec:
      # 파드 안에 어떤 컨테이너를 생성할 것인지 정의
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana-oss:7.10.2
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
          ports:
            - containerPort: 5601
              name: kibana-port
          volumeMounts:
            - mountPath: /usr/share/kibana/config/kibana.yml
              name: config
              subPath: kibana.yml
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: kibana-config
            items:
              - key: kibana.yml
                path: kibana.yml