server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/channel_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      encoding: UTF-8
  cloud:
    config:
      enabled: false
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: channel-system-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

jwe:
  secret-key: ${JWE_SECRET_KEY}

logging:
  level:
    org.springframework.kafka: INFO
    org.apache.kafka: INFO