server:
  port: 8080

spring:
  application:
    name: channel-banking
  datasource:
    url: jdbc:mysql://localhost:3308/channel_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      encoding: UTF-8
  cloud:
    config:
      enabled: false
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: channel-system-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

jwe:
  secret-key: ${JWE_SECRET_KEY}

feign:
  client:
    config:
      default:
        # 연결 타임아웃
        connectTimeout: 5000
        # 읽기 타임아웃
        readTimeout: 10000

resilience4j:
  retry:
    instances:
      coreBankingTransfer:
        max-attempts: 3 # 3번 재시도
        wait-duration: 1s # 재시도 대기시간
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - feign.RetryableException
          - java.net.SocketTimeoutException # 이 예외일 때만 재시도
        ignore-exceptions:
          - com.bank.channelbanking.global.exception.PendingTransactionExistsException

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: B3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org.springframework.kafka: INFO
    org.apache.kafka: INFO
    io.micrometer: DEBUG
    org.springframework.boot.actuate: DEBUG
    com.bank.channelbanking.config.FeignConfig: INFO
    feign: DEBUG