input {
  beats {
    port => 5044
    host => "0.0.0.0"
  }
}

filter {
  if [message] =~ /^\{.*\}$/ {
    json {
      source => "message"
      target => "log"
    }
  }

  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:log_level} \[%{DATA:thread}\] %{DATA:logger} : %{GREEDYDATA:log_message}"
    }
  }

  date {
    match => [ "timestamp", "ISO8601", "yyyy-MM-dd HH:mm:ss.SSS" ]
    target => "@timestamp"
  }

  if [log_message] =~ /transfer|transaction|account/ {
    mutate {
      add_field => { "log_type" => "transaction" }
    }
  }

  if [log_message] =~ /authentication|authorization|login|jwt|jwe/ {
    mutate {
      add_field => { "log_type" => "security" }
    }
  }

  if [log_message] =~ /Request|Response|Controller/ {
    mutate {
      add_field => { "log_type" => "api" }
    }
  }

  if [log_level] == "ERROR" {
    mutate {
      add_field => { "log_type" => "error" }
      add_tag => [ "error" ]
    }
  }

  mutate {
    remove_field => [ "agent", "ecs", "input", "host" ]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "channel-banking-logs-%{+YYYY.MM.dd}"

  }

}
